name: ipotato_timer
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^2.10.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.0.0
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.0
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  assets_audio_player: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  drift_dev: ^2.10.0  
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
 